//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TSB.Services.CIF.Manager.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CIFv2Entities : DbContext
    {
        public CIFv2Entities()
            : base("name=CIFv2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CustCellphone> CustCellphones { get; set; }
        public virtual DbSet<CustMail> CustMails { get; set; }
        public virtual DbSet<CustMain> CustMains { get; set; }
    }
}
