//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TSB.Services.CIF.Manager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustMain
    {
        public string CustID { get; set; }
        public string CustPermID { get; set; }
        public string CustStatus { get; set; }
    
        public virtual CustCellphone CustCellphone { get; set; }
        public virtual CustMail CustMail { get; set; }
    }
}
